#!/bin/bash

# author: vendrim 
# time of creation: 05.06.2019

# simple script for people who are too lazy to type all of these
# every time in to the terminal
# updates system and cleans it.
# will also fix simple problems like dependencies and such

sudo apt update
sudo apt upgrade
sudo apt autoremove
sudo apt -f install
echo "apt done!"
sudo apt-get update
sudo apt-get upgrade
sudo apt-get autoremove
sudo apt-get -f install
echo "apt-get done. All is up to date"
